'''Constant string literals used throughout the API'''

ADM0 = 'adm0'
ADM1 = 'adm1'

COUNTRY = 'country'
ALL = 'all'
OVERALL = 'overall'
OR = ","
YEAR = 'year'
LATEST = 'latest'
OLDEST = 'oldest'
IRR = 'irrigated'
RFD = 'rainfed'
LATEST_BY_GEO = 'latest_by_geo'
GENDER = 'gender'
RURAL = 'rural'
RESIDENCE = 'residence'
POVERTY_LEVEL = 'poverty_level'
WATER_SUPPLY = 'water_supply'
MALE = 'male'
FEMALE = 'female'
PPP1 = 'ppp1'
PPP2 = 'ppp2'
URBAN = 'urban'
RURAL = 'rural'
MODERATE = 'moderate'
SEVERE = 'severe'
STUNTED = 'stunted'
WASTED = 'wasted'
UNDERWEIGHT = 'underweight'
